---

# https://github.com/wayofdev/gh-actions/blob/master/.github/workflows/create-release.yml
# https://github.com/google-github-actions/release-please-action#release-types-supported

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master

name: ðŸ“¦ Create release

jobs:
  release:
    uses: wayofdev/gh-actions/.github/workflows/create-release.yml@master
    with:
      os: ubuntu-latest
      branch: master
      package-name: laravel-cycle-orm-adapter
    secrets:
      token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

...
